server:
  port: 8080
spring:
  redis:
    host: localhost
    password: XXXXX #your password
    port: 6379
    database: 0 #default database 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 2


